### ISSUE TITLE
COPY "metrics_copy" FROM STDIN hogs a lot of CPU

### ISSUE THREAD

**Issue by DeathBorn** [timescale/pg_prometheus#6]
32 core CPU, 256 GB RAM, Raid 10 of HDD for TimescaleDB (single tablespace), pg_prometheus extension
```
archive_command = 'envdir /etc/patroni/patroni.env.d wal-e wal-push %p'
archive_mode = 'on'
archive_timeout = '1800s'
bgwriter_delay = '200ms'
bgwriter_flush_after = '0'
bgwriter_lru_maxpages = '100'
bgwriter_lru_multiplier = '2.0'
checkpoint_completion_target = '0.9'
checkpoint_timeout = '15 min'
cluster_name = 'poclts'
effective_cache_size = '179 GB'
effective_io_concurrency = '0'
hot_standby = 'on'
huge_pages = 'off'
listen_addresses = '127.0.0.1,sprvrt001.zone'
log_destination = 'csvlog'
log_filename = 'postgresql'
log_min_duration_statement = '1000'
log_statement = 'ddl'
log_timezone = 'UTC'
logging_collector = 'True'
maintenance_work_mem = '1920 MB'
max_connections = '100'
max_locks_per_transaction = '64'
max_parallel_workers = '24'
max_parallel_workers_per_gather = '12'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_wal_size = '10240 MB'
max_worker_processes = '24'
min_wal_size = '5120 MB'
pg_stat_statements.max = '5000'
pg_stat_statements.save = 'True'
pg_stat_statements.track = 'all'
port = '5432'
shared_buffers = '65536 MB'
shared_preload_libraries = 'pg_stat_statements,timescaledb'
superuser_reserved_connections = '3'
track_commit_timestamp = 'off'
wal_buffers = '-1'
wal_compression = 'True'
wal_keep_segments = '1290'
wal_level = 'replica'
wal_log_hints = 'on'
work_mem = '128 MB'
```

Single Prometheus 2. server collecting metrics from 180 node-exporters.
```
remote_write:
- url http://prometheus_postgresql_adapter:9201/write
  remote_timeout: 30s
  queue_config:
    capacity: 100000
    max_shards: 100
    max_samples_per_send: 5000
    batch_send_deadline: 5s
    max_retries: 10
    min_backoff: 30ms
    max_backoff: 100ms
```

![htop](https://user-images.githubusercontent.com/228085/38564159-3c63df9a-3ce7-11e8-92f6-174bffe38c95.png)

Just over 1 hour we got ~15gb of data inside PostgreSQL.  Just by adding second Prometheus server CPU% usage increased by 20% more. We will have many more Prometheus servers. Will need to keep 2 years data.
Found this https://wiki.postgresql.org/wiki/COPY and but no answer.
This is completely unacceptable.

Maybe you have a hunch what we are doing wrong?
